name: "Dive Action"
description: "Run Dive to analyze the container image efficiency"
author: "@yuichielectric"
branding:
  icon: "aperture"
  color: "green"
inputs:
  image:
    description: "Image to analyze"
    required: true
  dive-version:
    description: "Docker Dive version"
    required: false
    default: latest
  config-file:
    description: "Path to dive config file"
    required: false
    default: ${{ github.workspace }}/.dive.yaml
  github-token:
    description: "GitHub Token to post PR comment"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
